import "../globals.css";
import "@/style/prosemirror.css";
import { Inter } from "next/font/google";
import { Providers } from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="h-full w-full">{children}</main>
        </Providers>
      </body>
    </html>
  );
};

export default Layout;
